// frontend/src/Components/Login/Login.jsx
import React from 'react'
import './Login.scss'
import '../../App.scss'

const Login = () => {
    return (
        <>
        <title>Login</title>
        <div className='login'>
            <div className='login__container'>
                <h1 className='login__title'>Welcome Back!</h1>
                <form className='login__form'>
                    <div className='login__form-group'>
                        <input required type='email'placeholder='Email'className='login__input'/>
                    </div>
                    <div className='login__form-group'>
                        <input required type='password' Placeholder='Password' className='login__input' />
                    </div>
                    <button type='submit' className='login__button'>Sign In</button>
                    <div className='login__footer'>
                       {/* <a href='#' className='login__link'>Forgot Password?</a> */}
                        <a href='./register' className='login__link'>Create Account</a>
                    </div>
                </form>
            </div>
        </div>
    </>
    );
};

export default Login

// frontend/src/pages/Login.vue
<template>
    <div class="login-container">
      <h2>Login</h2>
      <form @submit.prevent="login">
        <input v-model="email" type="email" placeholder="Email" required />
        <input v-model="password" type="password" placeholder="Password" required />
        <button type="submit">Login</button>
      </form>
      <p>Don't have an account? <router-link class="primary" to="/register">Register</router-link></p>
    </div>
  </template>
  
  <script>
  import { useAuthStore } from '../store/authStore';
  
  export default {
    data() {
      return {
        email: '',
        password: '',
      };
    },
    methods: {
      async login() {
        const authStore = useAuthStore();
        try {
          await authStore.login({ email: this.email, password: this.password });
          this.$router.push('/dashboard');
        } catch (error) {
          alert('Login failed');
        }
      },
    },
  };
  </script>
  
  <style lang="scss" scoped>
    @import '../style/style.scss';
  </style>
